name: Validate deployment when PR is created
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - force-app/**
    branches:
      - develop
jobs:
  validate-deployment-when-pr-is-created:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Salesforce CLI
        run: >
          wget
          https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz

          mkdir ~/sf

          tar xJf sf-linux-x64.tar.xz -C ~/sf --strip-components 1

          echo "$HOME/sf/bin" >> $GITHUB_PATH

          ~/sf/bin/sf version
      - name: Populate auth file with SFDX_URL secret of target org
        run: |
          echo ${{ secrets.PROD_URL}} > ./PROD_URL.txt
      - name: Authenticate to target Org
        run: sf org login sfdx-url -f ./PROD_URL.txt -s -a targetOrg
      - name: Installing sfdx git delta
        run: |
          echo y | sf plugins install sfdx-git-delta
          sf plugins 
      - name: Create delta packages for new, modified or deleted metadata
        run: >
          mkdir changed-sources

          sf sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/
      - name: Installing java
        run: sudo apt-get update && sudo apt-get install default-jdk
      - name: Installing SFDX scanner
        run: sf plugins install @salesforce/sfdx-scanner
      - name: Scan code
        run: |
          cd changed-sources 
          sf scanner:run --format sarif --target 'changed-sources/**/(*.cls|*.trigger|*.js|*.html|*.page|*.cmp|*.component|*.apex|*.ts)' --category 'Design,Best Practices,Performance,Code Style,Security' --outfile 'apexScanResults.sarif' --engine 'pmd,cpd,eslint-lwc,retire-js'
          cd ..
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: changed-sources/apexScanResults.sarif
      - name: Read PR Body
        env:
          PR_BODY: ${{github.event.pull_request.body}}
        run: |
          
          echo *
          FILE="$PWD/parsePR.js"
          if [[ -f "$FILE" ]]; then
              echo $PR_BODY > ./pr_body.txt
              node "$PWD/parsePR.js"         
              TESTS=$(cat testsToRun.txt)
              echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
              echo "$TESTS"     
          else
              TESTS=all
              echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV
              echo "$TESTS" 
          fi
      - name: Deployment - run specified tests
        if: ${{ env.APEX_TESTS != 'all' }}
        run: >
          echo ${{env.APEX_TESTS}}

          sf project deploy start -d "changed-sources/force-app/" --dry-run --test-level RunSpecifiedTests  --target-org targetOrg --tests ${{env.APEX_TESTS}} --json
      - name: Deployment - run all tests
        if: ${{ env.APEX_TESTS == 'all' }}
        run: >
          echo ${{env.APEX_TESTS}}

           sf project deploy start -d "changed-sources/force-app/" --dry-run --test-level RunLocalTests --target-org targetOrg --json
